const words: string[][] = [
  ["Abstand"],
  ["Beschlüsse"],
  ["Bund und Länder"],
  ["Corona-Schutzverordnung"],
  ["Coronavirus", "Corona", "COVID-19", "Virus"],
  ["Einschränkungen", "Beschränkungen", "Kontaktbeschränkungen", "Ausgangsbeschränkungen"],
  ["gemeldeten Fällen", "Fallzahlen"],
  ["Gesundheitssystem"],
  ["Hausstand"],
  ["Hygienemaßnahmen"],
  ["Homeoffice"],
  ["Impfungen", "impfen", "Schutzimpfungen"],
  ["Impfzentrum", "Impfzentren"],
  ["Infektionszahlen"],
  ["Neuinfektionen", "Infektionen"],
  ["Inzidenz", "7-Tages-Inzidenz"],
  ["Kontaktpersonen"],
  ["Krise"],
  ["Lockdown"],
  ["Maßnahmen", "Verordnung"],
  ["Mund-Nasen-Bedeckung", "Mundschutz", "Mund-Nasen-Schutz", "Maske"],
  ["Neuinfektionen"],
  ["Pandemie"],
  ["Patienten"],
  ["Quarantäne"],
  ["r-Wert", "Reproduktionszahl"],
  ["Robert Koch-Institut", "RKI"],
  ["Schutzimpfungen"],
  ["Symptome"],
  ["Testergebnis"],
  ["Todesfälle"],
  ["Verlängerung"],
  ["Wirtschaft"],
];

export default words;