const words: string[][] = [
  ["Abstand", "Abstands<wbr>regelungen"],
  ["Beschlüsse", "Beschluss"],
  ["Bund und Länder"],
  ["Corona-<wbr>Schutzverordnung"],
  ["Coron<wbr>avirus", "Corona", "COVID-19", "Virus"],
  ["Einschränkungen", "Beschränkungen", "Kontakt<wbr>beschränkungen", "Ausgangs<wbr>beschränkungen"],
  ["gemeldete Fälle", "Fallzahlen"],
  ["Gesundheits<wbr>system"],
  ["Hausstand"],
  ["Hygiene<wbr>maßnahmen", "Nies<wbr>etikette"],
  ["Homeoffice", "Video<wbr>konferenz"],
  ["Risiko<wbr>gruppe", "Risiko<wbr>gruppen"],
  ["Risiko<wbr>gebiet"],
  ["Not<wbr>betreuung"],
  ["Reise<wbr>warnung"],
  ["Impfungen", "impfen", "Schutz<wbr>impfungen", "Impf<wbr>pflicht", "Impf<wbr>bereit<wbr>schaft"],
  ["Impf<wbr>zentrum", "Impfzentren"],
  ["Neu<wbr>infektionen", "Infektionen", "Infektions<wbr>zahlen", "Infektions-Schutzgesetz"],
  ["Inzidenz", "7-<wbr>Tage-<wbr>Inzidenz", "Inzidenz<wbr>wert"],
  ["Kontakt<wbr>personen", "Angehörige"],
  ["Krise", "Ausnahme<wbr>zustand"],
  ["Lockdown"],
  ["Maßnahmen", "Verordnung", "Regelungen"],
  ["Mund-<wbr>Nasen-<wbr>Bedeckung", "Mund<wbr>schutz", "Mund-<wbr>Nasen-<wbr>Schutz", "Maske", "FFP2-<wbr>Maske"],
  ["Pandemie"],
  ["Gesundheits<wbr>amt"],
  ["Intensiv<wbr>stationen"],
  ["Patienten"],
  ["system<wbr>relevant"],
  ["Besuchs<wbr>verbot"],
  ["Überlastung", "überlastet"],
  ["Quarantäne"],
  ["r-Wert", "Reproduktions<wbr>zahl"],
  ["Robert Koch-Institut", "RKI"],
  ["Schutz<wbr>impfungen"],
  ["Symptome"],
  ["Test<wbr>ergebnis", "Schnell<wbr>test", "PCR-Test", "Test<wbr>zentrum"],
  ["Todes<wbr>fälle"],
  ["Verlängerung"],
  ["Wirtschaft"],
];

export default words;